package info.startupbuilder.aws.cert.backend.dynamodb.app.core;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;
import org.springframework.hateoas.RepresentationModel;

import java.time.LocalDateTime;

@EqualsAndHashCode(callSuper = true)
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Question")
public class Question extends RepresentationModel<Question> {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    private String value;

//    @DynamoDBTypeConvertedTimestamp
//    private LocalDateTime askTime;

}
